### ISSUE TITLE
std::shared_ptr<rclcpp_lifecycle::LifecycleNode> controller_interface::ControllerInterfaceBase::node_’ is private within this context

### ISSUE THREAD

**Issue by robotcopper** [mateusmenezes95/omnidirectional_controllers#1]
Hello,

first of all, thank you for your wonderful work. 

I am currently trying to use it for my own 3-wheel omnidirectional robot project under ROS 2 Humble. However, after successfully resolving an initial issue with the inclusion: #include "tf2/LinearMath/Quaternion.h" without difficulty. I am now encountering hundreds of error messages, all with the same origin: 
error: ‘std::shared_ptr<rclcpp_lifecycle::LifecycleNode> controller_interface::ControllerInterfaceBase::node_’ is private within this context. 

I cannot seem to figure out where the problem is, considering that the only modification I have made so far is adding tf2 and tf2_ros to the packages in the CMakeLists to address the previously mentioned dependency issue. Would you be able to shed some light on the matter?

**Comment by mateusmenezes95** [comment]
Hello @robotcopper, thank you!

I am happy the other robotics developers are using my package.

The problem is most likely due to incompatible ROS2 versions. I developed this controller on Foxy Fitzroy, the first Long Time Support (LTS) version. Therefore, it is expected that there will be sudden API changes between Foxy and Humble, especially since the Foxy version was the first LTS version. I recommend two ways:

1. If possible, test the controller in the ROS2 Foxy;
2. If option 1 is not viable, try to figure out the line of the code breaking the compilation when using the Humble version. You can share the build log here so I can try to help you.

Unfortunately, at the moment, I don't have time to port the controller to the Humble or even the Iron Irwin (the last LTS version).

**Comment by robotcopper** [comment]
Thank you for your fast answer. 

After hours spent on my errors, I finally got it by changing "node_" in the omnidirectional_controller.cpp to "this->get_node()". 

Another error was in omnidirectional_controller.hpp: in both "controller_interface::return_type" declarations, the "override" declaration was not appreciated, so I took the risk to remove it ["override"].

Finally, only one error persists, which is the following:

"/opt/ros/humble/include/class_loader/class_loader/meta_object.hpp: In instantiation of ‘B* class_loader::impl::MetaObject<C, B>::create() const [with C = omnidirectional_controllers::OmnidirectionalController; B = controller_interface::ControllerInterface]’:
/opt/ros/humble/include/class_loader/class_loader/meta_object.hpp:216:7:   required from here
/opt/ros/humble/include/class_loader/class_loader/meta_object.hpp:218:12: error: invalid new-expression of abstract class type ‘omnidirectional_controllers::OmnidirectionalController’
  218 |     return new C;
      |            ^~~~~
In file included from /home/floris/ros2_ws/src/omnidirectional_controllers/src/omnidirectional_controller.cpp:23:
/home/floris/ros2_ws/src/omnidirectional_controllers/include/omnidirectional_controllers/omnidirectional_controller.hpp:45:7: note:   because the following virtual functions are pure within ‘omnidirectional_controllers::OmnidirectionalController’:
   45 | class OmnidirectionalController : public controller_interface::ControllerInterface {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/ros/humble/include/controller_interface/controller_interface.hpp:22,
                 from /home/floris/ros2_ws/src/omnidirectional_controllers/include/omnidirectional_controllers/omnidirectional_controller.hpp:30,
                 from /home/floris/ros2_ws/src/omnidirectional_controllers/src/omnidirectional_controller.cpp:23:
/opt/ros/humble/include/controller_interface/controller_interface_base.hpp:132:26: note:     ‘virtual rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn controller_interface::ControllerInterfaceBase::on_init()’
  132 |   virtual CallbackReturn on_init() = 0;
      |                          ^~~~~~~
/opt/ros/humble/include/controller_interface/controller_interface_base.hpp:144:23: note:     ‘virtual controller_interface::return_type controller_interface::ControllerInterfaceBase::update(const rclcpp::Time&, const rclcpp::Duration&)’
  144 |   virtual return_type update(const rclcpp::Time & time, const rclcpp::Duration & period) = 0;
      |                       ^~~~~~"

I'm not very comfortable with C++, but this error is unlike any I have encountered before. Any advice?

**Comment by mateusmenezes95** [comment]
The problem that you are facing is due to the class inheritance chain. Please, share the repository with me. I will try to solve the problem from this point.

**Comment by robotcopper** [comment]
Oh thank you verymutch because i feel quite lost in front of this error. my repository is here: https://github.com/robotcopper/omnidirectional_controllers_humble (it's temporary public to let you access it but i will change that after. I'm not use to github when it's about public sharing. Hope you don't mind). 

You will see that i did not make a lot of changes. I faced the error pretty fast. I hope you will be able to help me.

**Comment by mateusmenezes95** [comment]
Thank you @robotcopper 

So, I took advantage of what you had already done and implemented the port straight here in my repository. The inheritance problem was actually simple to solve. To help you understand what was done, take a look at the commit https://github.com/mateusmenezes95/omnidirectional_controllers/commit/66ac7599f9de699dd914fe91719a6f45b29def19. Please try to use the new humble branch of this repository. If you have any more problems, you can talk here

**Comment by robotcopper** [comment]
Thank you so much for your help. I had identified a few points but it seems I still have a lot to learn. 

I have what I hope is a final question: 

I'm getting from nav2 the path that my robot should follow on the cmd_vel topic. 
When I launch the controller I get this message: 

[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [54652]
[INFO] [spawner-2]: process started with pid [54654]
[INFO] [spawner-3]: process started with pid [54656]
[robot_state_publisher-1] [INFO] [1695159779.103751753] [robot_state_publisher]: got segment base_link
[robot_state_publisher-1] [INFO] [1695159779.103905924] [robot_state_publisher]: got segment robot_base
[robot_state_publisher-1] [INFO] [1695159779.103917422] [robot_state_publisher]: got segment roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.103925008] [robot_state_publisher]: got segment roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.103932282] [robot_state_publisher]: got segment roueholonome3
[robot_state_publisher-1] [INFO] [1695159779.103939557] [robot_state_publisher]: got segment rouleau_10_roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.103947544] [robot_state_publisher]: got segment rouleau_10_roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.103954758] [robot_state_publisher]: got segment rouleau_10_roueholonome3
[robot_state_publisher-1] [INFO] [1695159779.103961945] [robot_state_publisher]: got segment rouleau_1_roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.103969292] [robot_state_publisher]: got segment rouleau_1_roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.103977096] [robot_state_publisher]: got segment rouleau_1_roueholonome3
[robot_state_publisher-1] [INFO] [1695159779.103984288] [robot_state_publisher]: got segment rouleau_2_roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.103991351] [robot_state_publisher]: got segment rouleau_2_roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.103998197] [robot_state_publisher]: got segment rouleau_2_roueholonome3
[robot_state_publisher-1] [INFO] [1695159779.104005269] [robot_state_publisher]: got segment rouleau_3_roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.104012256] [robot_state_publisher]: got segment rouleau_3_roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.104019646] [robot_state_publisher]: got segment rouleau_3_roueholonome3
[robot_state_publisher-1] [INFO] [1695159779.104026771] [robot_state_publisher]: got segment rouleau_4_roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.104033732] [robot_state_publisher]: got segment rouleau_4_roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.104040805] [robot_state_publisher]: got segment rouleau_4_roueholonome3
[robot_state_publisher-1] [INFO] [1695159779.104047774] [robot_state_publisher]: got segment rouleau_5_roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.104054764] [robot_state_publisher]: got segment rouleau_5_roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.104061631] [robot_state_publisher]: got segment rouleau_5_roueholonome3
[robot_state_publisher-1] [INFO] [1695159779.104068523] [robot_state_publisher]: got segment rouleau_6_roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.104075545] [robot_state_publisher]: got segment rouleau_6_roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.104082478] [robot_state_publisher]: got segment rouleau_6_roueholonome3
[robot_state_publisher-1] [INFO] [1695159779.104089528] [robot_state_publisher]: got segment rouleau_7_roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.104096587] [robot_state_publisher]: got segment rouleau_7_roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.104103544] [robot_state_publisher]: got segment rouleau_7_roueholonome3
[robot_state_publisher-1] [INFO] [1695159779.104110359] [robot_state_publisher]: got segment rouleau_8_roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.104117284] [robot_state_publisher]: got segment rouleau_8_roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.104124203] [robot_state_publisher]: got segment rouleau_8_roueholonome3
[robot_state_publisher-1] [INFO] [1695159779.104131210] [robot_state_publisher]: got segment rouleau_9_roueholonome1
[robot_state_publisher-1] [INFO] [1695159779.104138010] [robot_state_publisher]: got segment rouleau_9_roueholonome2
[robot_state_publisher-1] [INFO] [1695159779.104144991] [robot_state_publisher]: got segment rouleau_9_roueholonome3
[spawner-3] [INFO] [1695159781.569493163] [spawner_omnidirectional_controller]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1695159781.596025643] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-3] [INFO] [1695159783.584770114] [spawner_omnidirectional_controller]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1695159783.610347147] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-3] [INFO] [1695159785.596846338] [spawner_omnidirectional_controller]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1695159785.621057977] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-3] [INFO] [1695159787.610726422] [spawner_omnidirectional_controller]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1695159787.641140015] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-3] [ERROR] [1695159789.623725742] [spawner_omnidirectional_controller]: Controller manager not available
[spawner-2] [ERROR] [1695159789.655433466] [spawner_joint_state_broadcaster]: Controller manager not available
[ERROR] [spawner-3]: process has died [pid 54656, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner omnidirectional_controller -c /controller_manager --ros-args'].
[ERROR] [spawner-2]: process has died [pid 54654, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner joint_state_broadcaster --controller-manager /controller_manager --ros-args'].


Have you encountered this error before? Do you know where the problem could be coming from?

**Comment by robotcopper** [comment]
I apologize for asking such basic questions, but between my discovery of ros2_control and its controllers and my obvious shortcomings in C++, I don't understand everything. Fundamentally, I don't understand how your package retrieves odometry.

    Doesn't it retrieve it from the /odom topic? If not (which is what I understood), what role does your package play?

    Does it take a desired global velocity from the /cmd_vel topic and then publish the velocity of each motor on a topic? If not, how is this provided as output?

    To function, it also needs to provide odometry, which in your case, the package directly retrieves from the motor encoders, right? In that case, how is this implemented in the package?

    In my case, my odometry is on the /odom topic. How can I use this odometry instead of the encoder-based one you've implemented?

Please excuse my incompetence and my lack of knowledge on the subject.

**Comment by robotcopper** [comment]
Thank you so much for your help @mateusmenezes95 .

**Comment by robotcopper** [comment]
Thank you so much for your help @mateusmenezes95.
