### ISSUE TITLE
[ros2_control_node-7] [ERROR] [controller_manager]: Can't activate controller 'omnidirectional_controller': State interface with key 'joint_name/velocity' does not exist

### ISSUE THREAD

**Issue by robotcopper** [mateusmenezes95/omnidirectional_controllers#8]
Hello @mateusmenezes95 ,

I am trying to use your controller in addition of the [topic_based_ros2_control](https://github.com/PickNikRobotics/topic_based_ros2_control/tree/main) hardware interface.

The thing is that on my real robot i do not need of state interface. Indeed I am controlling my robot in open loop. So as you can expect, i set the [```open_loop```](https://github.com/mateusmenezes95/axebot/blob/6327cdafae899ddf33ada79fc18216b6d90b6756/axebot_control/config/omnidirectional_controller.yaml#L30) param to ```True``` and as i saw it in the [```omnidirectional_controller.cpp```](https://github.com/mateusmenezes95/omnidirectional_controllers/blob/dd54b9c8a6b0a48ca9ff360b27404e4e1385b6ec/src/omnidirectional_controller.cpp#L346) it indeed unset the use of the state estimation tool.

However, in the ```omnidirectional_controller.cpp``` the controller keep looking for a [```state_interface```](https://github.com/mateusmenezes95/omnidirectional_controllers/blob/dd54b9c8a6b0a48ca9ff360b27404e4e1385b6ec/src/omnidirectional_controller.cpp#L234C1-L237C10) even if the ```open_loop``` is ```True```. 

Or we could expect that only command would be send in ```open_loop```, so in other words, just needing [```command_interface```](https://github.com/mateusmenezes95/omnidirectional_controllers/blob/dd54b9c8a6b0a48ca9ff360b27404e4e1385b6ec/src/omnidirectional_controller.cpp#L244C1-L248C10) in the ```hardware_interface``` and not also a [```state_interface```](https://github.com/mateusmenezes95/omnidirectional_controllers/blob/dd54b9c8a6b0a48ca9ff360b27404e4e1385b6ec/src/omnidirectional_controller.cpp#L234C1-L237C10) am i right? 

So is it a bug? Did I miss something?

Here is what i expect to implement as  ```hardware_interface```:
![image](https://github.com/mateusmenezes95/omnidirectional_controllers/assets/95591405/d063c947-88e9-4a1f-818b-a068d51d566d)

PS: Thank you again for this very useful work you have made

**Comment by mateusmenezes95** [comment]
Hello @robotcopper!

Thank you so much for your great description of the issue. And you are right: It's a bug.

Do you want propose a PR fixing it?

**Comment by robotcopper** [comment]
> Hello @robotcopper!
> 
> Thank you so much for your great description of the issue. And you are right: It's a bug.
> 
> Do you want propose a PR fixing it?

Hello @mateusmenezes95 , no problem. I made one. I tested it in open and closed loops and no regression appeared.

**Comment by mateusmenezes95** [comment]
Fixed in #9
